from __future__ import annotations

from datetime import timedelta

from django.db import models
from django.db.models import Manager
from django.utils import timezone


class App(models.Model):
    """
    Represents one of the user's iOS apps.

    Used for organizing keywords into groups — each keyword can
    optionally be associated with an app.

    When added via App Store lookup, track_id stores the iTunes
    numeric ID so we can find the app's rank in search results.
    """

    id: int  # Auto-generated by Django, declared for type checkers
    keywords: Manager[Keyword]

    name = models.CharField(max_length=200)
    bundle_id = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="e.g., com.example.myapp",
    )
    track_id = models.BigIntegerField(
        null=True,
        blank=True,
        unique=True,
        help_text="iTunes trackId — used for rank tracking in search results",
    )
    store_url = models.URLField(
        blank=True,
        default="",
        help_text="App Store URL",
    )
    icon_url = models.URLField(
        blank=True,
        default="",
        help_text="App icon URL from iTunes",
    )
    seller_name = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="Developer/publisher name",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Keyword(models.Model):
    """
    A keyword being tracked for ASO research.

    Can optionally be linked to an App for categorization.
    """

    id: int  # Auto-generated by Django, declared for type checkers
    results: Manager[SearchResult]

    keyword = models.CharField(max_length=200)
    app = models.ForeignKey(
        App,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="keywords",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("keyword", "app")
        ordering = ["-created_at"]

    def __str__(self):
        if self.app:
            return f"{self.keyword} ({self.app.name})"
        return self.keyword


class SearchResult(models.Model):
    """
    Stores the result of a keyword search at a point in time.

    Contains popularity score (from Apple), difficulty score (calculated),
    and the raw competitor data from iTunes Search API.
    """

    id: int  # Auto-generated by Django, declared for type checkers

    SOURCE_MANUAL_SEARCH = "manual_search"
    SOURCE_MANUAL_REFRESH = "manual_refresh"
    SOURCE_BULK_REFRESH = "bulk_refresh"
    SOURCE_DAILY_REFRESH = "daily_refresh"
    SOURCE_OPPORTUNITY_SAVE = "opportunity_save"
    SOURCE_AI_SUGGESTION = "ai_suggestion"

    SOURCE_CHOICES = [
        (SOURCE_MANUAL_SEARCH, "Manual Search"),
        (SOURCE_MANUAL_REFRESH, "Manual Refresh"),
        (SOURCE_BULK_REFRESH, "Bulk Refresh"),
        (SOURCE_DAILY_REFRESH, "Daily Refresh"),
        (SOURCE_OPPORTUNITY_SAVE, "Opportunity Save"),
        (SOURCE_AI_SUGGESTION, "AI Suggestion"),
    ]

    keyword = models.ForeignKey(
        Keyword,
        on_delete=models.CASCADE,
        related_name="results",
    )
    popularity_score = models.IntegerField(
        null=True,
        blank=True,
        help_text="1-100 estimated popularity score.",
    )
    difficulty_score = models.IntegerField(
        help_text="1-100 calculated difficulty score",
    )
    difficulty_breakdown = models.JSONField(
        default=dict,
        help_text="Component scores breakdown",
    )
    competitors_data = models.JSONField(
        default=list,
        help_text="Array of top competitor app dicts from iTunes",
    )
    app_rank = models.IntegerField(
        null=True,
        blank=True,
        help_text="App's 1-indexed rank in top-200 iTunes results (null if not found)",
    )
    country = models.CharField(
        max_length=5,
        default="us",
        help_text="Country code used for this search",
    )
    source = models.CharField(
        max_length=32,
        choices=SOURCE_CHOICES,
        default=SOURCE_MANUAL_SEARCH,
        db_index=True,
    )
    searched_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-searched_at"]
        indexes = [
            models.Index(
                fields=["keyword", "country", "-searched_at"],
                name="aso_kw_country_srch_idx",
            ),
        ]

    def __str__(self):
        return f"{self.keyword.keyword} — {self.searched_at:%Y-%m-%d %H:%M}"

    @classmethod
    def upsert_today(cls, keyword, country, **fields):
        """
        Create or replace today's result for a keyword+country pair.

        If a result already exists for today, delete it and create a fresh one.
        This ensures exactly one data point per keyword per country per day.
        """
        today_start = timezone.now().replace(hour=0, minute=0, second=0, microsecond=0)
        today_end = today_start + timedelta(days=1)
        cls.objects.filter(
            keyword=keyword,
            country=country,
            searched_at__gte=today_start,
            searched_at__lt=today_end,
        ).delete()
        return cls.objects.create(keyword=keyword, country=country, **fields)

    @classmethod
    def create_snapshot(
        cls,
        *,
        keyword,
        country,
        source=SOURCE_MANUAL_SEARCH,
        **fields,
    ):
        """
        Always create a new historical snapshot.

        This is append-only and preserves intra-day history.
        """
        return cls.objects.create(
            keyword=keyword,
            country=country,
            source=source,
            **fields,
        )

    @property
    def difficulty_label(self):
        """Human-readable difficulty interpretation."""
        score = self.difficulty_score
        if score <= 15:
            return "Very Easy"
        elif score <= 35:
            return "Easy"
        elif score <= 55:
            return "Moderate"
        elif score <= 75:
            return "Hard"
        elif score <= 90:
            return "Very Hard"
        return "Extreme"

    @property
    def difficulty_color(self):
        """Tailwind color class for the difficulty score."""
        score = self.difficulty_score
        if score <= 15:
            return "text-green-400"
        elif score <= 35:
            return "text-green-300"
        elif score <= 55:
            return "text-yellow-400"
        elif score <= 75:
            return "text-orange-400"
        elif score <= 90:
            return "text-red-400"
        return "text-red-600"

    @property
    def targeting_advice(self):
        """Return (icon, label, css_classes, description) for ASO targeting."""
        diff = self.difficulty_score
        pop = self.popularity_score

        if pop is not None:
            if pop >= 40 and diff <= 40:
                return ("🎯", "Sweet Spot", "bg-green-900/20 text-green-300 border-green-500/20",
                        "High popularity + low difficulty — ideal keyword to target with good ASO.")
            elif pop >= 40 and diff <= 60:
                return ("✅", "Good Target", "bg-green-900/20 text-green-300 border-green-500/20",
                        "Solid popularity with manageable difficulty.")
            elif pop >= 40 and diff > 60:
                return ("⚔️", "Worth Competing", "bg-yellow-900/20 text-yellow-300 border-yellow-500/20",
                        "High demand but tough competition. Consider long-tail variants.")
            elif 30 <= pop < 40 and diff <= 40:
                return ("💎", "Hidden Gem", "bg-blue-900/20 text-blue-300 border-blue-500/20",
                        "Moderate volume with little competition. Good for niche apps.")
            elif 30 <= pop < 40 and diff <= 60:
                return ("👍", "Decent Option", "bg-slate-800 text-slate-300 border-white/10",
                        "Moderate demand and competition. Can work as a supporting keyword.")
            elif pop < 30 and diff <= 30:
                return ("🔍", "Low Volume", "bg-slate-800 text-slate-300 border-white/10",
                        "Easy to rank but few people search for this. Best as a supporting keyword.")
            elif pop < 30 and diff > 30:
                return ("🚫", "Avoid", "bg-red-900/20 text-red-300 border-red-500/20",
                        "Low search volume with notable competition.")
            else:
                return ("⚔️", "Challenging", "bg-yellow-900/20 text-yellow-300 border-yellow-500/20",
                        "Strong competition. Focus on long-tail variants.")
        else:
            if diff <= 25:
                return ("🟢", "Easy to Rank", "bg-green-900/20 text-green-300 border-green-500/20",
                        "Low competition — a well-optimized app can rank quickly.")
            elif diff <= 50:
                return ("🟡", "Moderate", "bg-yellow-900/20 text-yellow-300 border-yellow-500/20",
                        "Achievable with strong ASO.")
            elif diff <= 75:
                return ("🟠", "Competitive", "bg-orange-900/20 text-orange-300 border-orange-500/20",
                        "Consider long-tail variants.")
            else:
                return ("🔴", "Very Competitive", "bg-red-900/20 text-red-300 border-red-500/20",
                        "Dominated by established apps. Target easier keywords first.")


class RefreshRun(models.Model):
    """Tracks a full refresh execution lifecycle for status and auditing."""

    TRIGGER_CRON = "cron"
    TRIGGER_MANUAL = "manual"
    TRIGGER_THREAD = "thread"
    TRIGGER_CHOICES = [
        (TRIGGER_CRON, "Cron"),
        (TRIGGER_MANUAL, "Manual"),
        (TRIGGER_THREAD, "Thread Scheduler"),
    ]

    STATUS_RUNNING = "running"
    STATUS_SUCCESS = "success"
    STATUS_FAILED = "failed"
    STATUS_CHOICES = [
        (STATUS_RUNNING, "Running"),
        (STATUS_SUCCESS, "Success"),
        (STATUS_FAILED, "Failed"),
    ]

    trigger = models.CharField(max_length=16, choices=TRIGGER_CHOICES)
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default=STATUS_RUNNING)
    total = models.PositiveIntegerField(default=0)
    completed = models.PositiveIntegerField(default=0)
    current_keyword = models.CharField(max_length=255, blank=True, default="")
    started_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(null=True, blank=True)
    error = models.TextField(blank=True, default="")

    class Meta:
        ordering = ["-started_at"]

    @classmethod
    def latest_status_payload(cls):
        latest = cls.objects.order_by("-started_at").first()
        if not latest:
            return {
                "running": False,
                "total": 0,
                "completed": 0,
                "current_keyword": "",
                "started_at": None,
                "last_completed_at": None,
                "error": None,
            }
        return {
            "running": latest.status == cls.STATUS_RUNNING,
            "total": latest.total,
            "completed": latest.completed,
            "current_keyword": latest.current_keyword,
            "started_at": latest.started_at.isoformat() if latest.started_at else None,
            "last_completed_at": (
                latest.finished_at.isoformat() if latest.status == cls.STATUS_SUCCESS and latest.finished_at else None
            ),
            "error": latest.error or None,
        }


class AISuggestionRun(models.Model):
    """Stores one AI suggestion generation run."""

    STATUS_RUNNING = "running"
    STATUS_SUCCESS = "success"
    STATUS_FAILED = "failed"
    STATUS_CHOICES = [
        (STATUS_RUNNING, "Running"),
        (STATUS_SUCCESS, "Success"),
        (STATUS_FAILED, "Failed"),
    ]

    app = models.ForeignKey(App, on_delete=models.CASCADE, related_name="ai_suggestion_runs")
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default=STATUS_RUNNING)
    model = models.CharField(max_length=100)
    countries_json = models.JSONField(default=list)
    input_snapshot_json = models.JSONField(default=dict)
    error = models.TextField(blank=True, default="")
    started_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-started_at"]

    def __str__(self):
        return f"AI run #{self.pk} for {self.app.name}"


class AISuggestion(models.Model):
    """Draft/accepted/rejected keyword suggestion generated by AI."""

    STATUS_DRAFT = "draft"
    STATUS_ACCEPTED = "accepted"
    STATUS_REJECTED = "rejected"
    STATUS_CHOICES = [
        (STATUS_DRAFT, "Draft"),
        (STATUS_ACCEPTED, "Accepted"),
        (STATUS_REJECTED, "Rejected"),
    ]

    run = models.ForeignKey(AISuggestionRun, on_delete=models.CASCADE, related_name="suggestions")
    app = models.ForeignKey(App, on_delete=models.CASCADE, related_name="ai_suggestions")
    keyword = models.CharField(max_length=200)
    intent = models.CharField(max_length=200, blank=True, default="")
    rationale = models.TextField(blank=True, default="")
    confidence = models.FloatField(default=0.0)
    score_market = models.FloatField(default=0.0)
    score_history = models.FloatField(default=0.5)
    score_overall = models.FloatField(default=0.0, db_index=True)
    market_metrics_json = models.JSONField(default=dict)
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default=STATUS_DRAFT, db_index=True)
    created_keyword = models.ForeignKey(
        Keyword,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="ai_suggestions",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-score_overall", "-created_at"]
        unique_together = ("run", "keyword")

    def __str__(self):
        return f"{self.keyword} ({self.status})"


class RuntimeConfig(models.Model):
    """
    Singleton runtime configuration overrides persisted in the DB.

    Values here override environment defaults and are stored in /app/data via SQLite.
    """

    singleton_key = models.PositiveSmallIntegerField(default=1, unique=True, editable=False)
    openai_api_key = models.CharField(max_length=255, blank=True, default="")
    openai_default_model = models.CharField(max_length=100, blank=True, default="")
    openai_available_models = models.TextField(
        blank=True,
        default="",
        help_text="Comma-separated list of models shown in the AI Suggestions dropdown.",
    )
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Runtime Config"
        verbose_name_plural = "Runtime Config"

    @classmethod
    def get_solo(cls):
        obj, _ = cls.objects.get_or_create(singleton_key=1)
        return obj

    def __str__(self):
        return "Runtime Config"
