from __future__ import annotations

from django.core.management.base import BaseCommand, CommandError

from ...models import RefreshRun, SearchResult
from ...refresh_service import run_refresh


class Command(BaseCommand):
    help = "Refresh tracked keyword-country pairs and store append-only history snapshots."

    def add_arguments(self, parser):
        parser.add_argument(
            "--trigger",
            choices=[RefreshRun.TRIGGER_CRON, RefreshRun.TRIGGER_MANUAL, RefreshRun.TRIGGER_THREAD],
            default=RefreshRun.TRIGGER_MANUAL,
            help="Execution source recorded in RefreshRun.",
        )
        parser.add_argument(
            "--force",
            action="store_true",
            help="Refresh all pairs even if daily_refresh already ran today.",
        )
        parser.add_argument(
            "--source",
            choices=[choice[0] for choice in SearchResult.SOURCE_CHOICES],
            default=SearchResult.SOURCE_DAILY_REFRESH,
            help="SearchResult.source value for snapshots generated by this command.",
        )

    def handle(self, *args, **options):
        try:
            run = run_refresh(
                trigger=options["trigger"],
                source=options["source"],
                force=bool(options["force"]),
            )
        except Exception as exc:  # pragma: no cover - defensive production path
            raise CommandError(str(exc)) from exc

        if run.status == RefreshRun.STATUS_FAILED:
            self.stderr.write(self.style.WARNING(f"Refresh completed with failures: {run.error}"))
        else:
            self.stdout.write(
                self.style.SUCCESS(
                    f"Refresh completed: {run.completed}/{run.total} pairs ({run.status})."
                )
            )
