# Generated by Django 6.0.3 on 2026-03-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0010_ai_copilot_and_asc_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicopilotrun',
            name='progress_detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aicopilotrun',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aicopilotrun',
            name='progress_stage',
            field=models.CharField(blank=True, default='queued', max_length=64),
        ),
    ]
