# Generated by Django 6.0.3 on 2026-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0011_aicopilotrun_progress_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicopilotrun",
            name="events_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="runtimeconfig",
            name="openai_reasoning_effort",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default reasoning effort for OpenAI requests (blank = auto).",
                max_length=16,
            ),
        ),
    ]
